version: 2.1
commands:
  install-dependencies:
    steps:
      - restore_cache:
          keys:
            - pg_failover-{{ checksum "pg_failover.gemspec" }}-{{ checksum "Gemfile" }}
      - run:
          name: Install Ruby gems
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
      - save_cache:
          key: pg_failover-{{ checksum "pg_failover.gemspec" }}-{{ checksum "Gemfile" }}
          paths:
            - vendor/bundle
  test:
    steps:
      - run:
          name: Run unit tests
          command: bundle exec rspec

executors:
  ruby:
    docker:
      - image: circleci/ruby:<< parameters.tag >>
    parameters:
      tag:
        description: "Docker image tag"
        default: "latest"
        type: string

jobs:
  build:
    executor:
      name: ruby
      tag: << parameters.tag >>
    parameters:
      tag:
        description: "Docker image tag"
        default: << parameters.tag >>
        type: string
    steps:
      - checkout
      - install-dependencies
      - test
  publish:
    executor:
      name: ruby
    steps:
      - checkout
      - install-dependencies
      - run:
          name: Build gem
          command: bundle exec rake build
      - run:
          name: Configure RubyGems API key
          command: |
            echo ":rubygems_api_key: $RUBYGEMS_API_KEY" >  ~/.gem/credentials
            chmod 0600 ~/.gem/credentials
      - run:
          name: Publish gem
          command: |
            package=$(ls -t1 pkg/pg_failover-*.gem | head -1)
            gem push "$package"

workflows:
  test-and-publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
          name: "ruby23"
          tag: "2.3"
      - build:
          filters:
            tags:
              only: /.*/
          name: "ruby24"
          tag: "2.4"
      - build:
          filters:
            tags:
              only: /.*/
          name: "ruby25"
          tag: "2.5"
      - build:
          filters:
            tags:
              only: /.*/
          name: "ruby26"
          tag: "2.6"
      - publish:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d{1,2}\.\d{1,2}\.\d{1,2}/
          requires:
            - ruby23
            - ruby24
            - ruby25
            - ruby26
